;;; Automatically generated by `recentf' on Thu Jan 21 14:37:03 2010.

(setq recentf-list
      '(
        "/Users/weeksie/.ido.last"
        "/Users/weeksie/Library/Preferences/Aquamacs Emacs/Preferences.el"
        "/Users/weeksie/Workspace/oro/lib/jda_importer.rb"
        "/Users/weeksie/Workspace/oro/spec/lib/jda_adjuster_spec.rb"
        "/Users/weeksie/Workspace/oro/lib/jda_adjuster.rb"
        "/Users/weeksie/Workspace/oro/db/jda/sql/store_inventory_adjustments.sql"
        "/Users/weeksie/Workspace/oro/db/jda/sql/store_inventories.sql"
        "/Users/weeksie/Workspace/oro/db/jda/importers/7_store_inventories.rb"
        "/Users/weeksie/Workspace/oro/db/jda/importers/1_stores.rb"
        "/Users/weeksie/Workspace/mongoforum/app/views/conversations/index.haml"
        "/Users/weeksie/Workspace/mongoforum/db/seeds.rb"
        "/Users/weeksie/Workspace/mongoforum/app/models/post.rb"
        "/Users/weeksie/Workspace/mongoforum/app/models/forum.rb"
        "/Users/weeksie/Workspace/mongoforum/app/models/conversation.rb"
        "/Users/weeksie/Workspace/mongoforum/app/controllers/conversations_controller.rb"
        "/Users/weeksie/Workspace/mongoforum/config/routes.rb"
        "/Users/weeksie/Workspace/oro/lib/tasks/all_jdas_import.rake"
        "/Users/weeksie/Workspace/oro/spec/lib/jda_importer_spec.rb"
        ))

(setq recentf-filter-changer-current 'nil)


;;; Local Variables:
;;; coding: emacs-mule
;;; End:
