;;; Automatically generated by `recentf' on Tue Jan 19 01:10:03 2010.

(setq recentf-list
      '(
        "/Users/weeksie/.ido.last"
        "/Users/weeksie/Writing/PEF/porno-en-fuego-part-2.tex"
        "/Users/weeksie/Writing/PEF/porno-en-fuego.tex"
        "/Users/weeksie/Workspace/heyfoxy.com/test/functional/flags_controller_test.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/test/functional/profiles_controller_test.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/test/functional/users_controller_test.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/app/controllers/users_controller.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/app/models/user.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/app/models/profile.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/app/models/search_preferences.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/test/factories/profile.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/test/factories/search_preferences.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/app/controllers/flags_controller.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/lib/authenticated_test_helper.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/app/models/flag.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/test/unit/flag_test.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/test/factories/flag.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/test/functional/albums_controller_test.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/lib/authenticated_system.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/app/helpers/application_helper.rb"
        ))

(setq recentf-filter-changer-current 'nil)


;;; Local Variables:
;;; coding: emacs-mule
;;; End:
