;;; Automatically generated by `recentf' on Mon Dec 14 01:10:03 2009.

(setq recentf-list
      '(
        "/Users/weeksie/.ido.last"
        "/Users/weeksie/Workspace/heyfoxy.com/app/stylesheets/screen.sass"
        "/Users/weeksie/Workspace/heyfoxy.com/app/views/sessions/_new.haml"
        "/Users/weeksie/Workspace/heyfoxy.com/app/controllers/sessions_controller.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/app/views/sessions/new.haml"
        "/Users/weeksie/Workspace/heyfoxy.com/test/functional/profiles_controller_test.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/lib/tasks/generate_data.rake"
        "/Users/weeksie/Workspace/heyfoxy.com/Rakefile"
        "/Users/weeksie/Workspace/heyfoxy.com/vendor/gems/forgery-0.3.0/README.markdown"
        "/Users/weeksie/Workspace/heyfoxy.com/vendor/gems/forgery-0.3.0/.specification"
        "/Users/weeksie/Workspace/heyfoxy.com/vendor/gems/forgery-0.3.0/lib/forgery/forgery/internet.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/vendor/gems/forgery-0.3.0/lib/forgery/forgery.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/vendor/gems/forgery-0.3.0/lib/forgery/dictionaries.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/vendor/gems/forgery-0.3.0/spec/forgery/basic_spec.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/vendor/gems/forgery-0.3.0/lib/forgery/forgery_api.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/vendor/gems/forgery-0.3.0/lib/forgery.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/test/unit/notification_test.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/app/models/notification.rb"
        "/Users/weeksie/Workspace/heyfoxy.com/app/views/profiles/show.haml"
        "/Users/weeksie/Workspace/heyfoxy.com/app/views/profiles/_new.haml"
        ))

(setq recentf-filter-changer-current 'nil)


;;; Local Variables:
;;; coding: emacs-mule
;;; End:
